site_name: Wildglade Chronicles Wiki
site_description: The official wiki for the Wildglade Chronicles game
site_author: PinkePop
site_url: https://wildglade-wiki.kylianv.dev./

theme:
  name: material
  copyright:
    text: "&copy; 2025-Present PinkePop – Wildglade Chronicles Wiki"
  palette:
    primary: blue grey
  language: fr
  features:
    - navigation.path
    - navigation.footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PinkePop/wildglade-wiki
      name: PinkePop

extra_css:
  - styles/extra.css

copyright: "&copy; 2025-Present PinkePop – Wildglade Chronicles Wiki"

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Accueil: index.md
  - L'Univers de Wildglade Chronicles:
    - Univers: lore/lore.md
  - Règles:
    - Règles: rules/rules.md
  - Création de personnage:
    - Espèces: character/species.md
